#!/bin/bash
set -x
# Run with either command:
# curl -fsSL https://raw.githubusercontent.com/yshinagawa/dotfiles/master/install | sh
# wget -qO- https://raw.githubusercontent.com/yshinagawa/dotfiles/master/install | sh

if [ -d "$HOME/.dotfiles" ]; then
    printf "\\033[31mError:\\033[0m ~/.dotfiles already exists.\\n" >&2
    exit 1
fi

if !(type git > /dev/null 2>&1); then
    sudo -E apt-get -q -y install git
fi

if !(type stow > /dev/null 2>&1); then
    sudo -E apt-get -q -y install stow
fi

git clone --recursive --depth=1 https://github.com/yshinagawa/dotfiles.git "$HOME/.dotfiles"
rm "$HOME/.bashrc"
cd "$HOME/.dotfiles" && make link
~/.bash/fzf/install --bin --no-update-rc

bash -i --login
