#!/usr/bin/env bash

# Set up liquidprompt
SOURCE_DIR="$(cd "$(dirname ${BASH_SOURCE:-$0})" && pwd)"
if [ -f "$SOURCE_DIR/liquidprompt/liquidprompt" ]; then
    source "$SOURCE_DIR/liquidprompt/liquidprompt";
fi;
