(require 'emmet-mode)
(add-hook 'sgml-mode-hook 'emmet-mode)
(add-hook 'css-mode-hook 'emmet-mode)
(add-hook 'emmet-mode-hook (lambda () (setq emmet-indent-after-insert nil)))
;(add-hook 'emmet-mode-hook (lambda () (setq emmet-indentation 2)))
;(setq emmet-move-cursor-between-quotes t)
